version: "3"
services:
  web:
    build:
      context: angular
      target: dev-envs
    ports:
      - 4200:4200
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /node_modules
